[package]
name = "blurhash-factory"
version = "0.1.1"
authors = ["Ardy Febriansyah <ardyfeb@juabali.com>"]
edition = "2018"

[dependencies]
prost = "0.7"
tonic = "0.4.0"
image = { features=["jpeg", "png"], version = "0.23.13" }
blurhash = { git = "https://github.com/ardyfeb/blurhash-rs", version = "0.1.2" }
reqwest = { default-features = false, features = ["rustls-tls"], version = "0.11.0"}
tokio = { features = ["rt", "macros", "sync", "rt-multi-thread"], version = "1.2.0" }
url = "2.2.0"

[build-dependencies]
tonic-build = "0.4.0"
